name: Build Blog and Deploy
on:
  push:
    branches:
      - source

jobs:
  build:
    name: Blog and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v4
        with:
              ref: 'source'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy
        run: |
          git config --global user.name  "Rainvisitor"
          git config --global user.email "abc873693@gmail.com"
          git remote add origin https://${{ secrets.ACCESS_TOKEN }}@github.com/abc873693/rainvisitor.githib.io.git
      - name: Install dependencies
        run: |
          npm i -g hexo-cli
          npm i
      - name: Deploy hexo
        run: |
          hexo generate && hexo deploy